# Starter Exploratory Data Analysis Notebook 

Here is a starter notebook to look at exploratory data analysis and preprocessing. More can be added and explored !

In [59]:
import pandas as pd

In [68]:
col_names = ['Time','Tweet','Favorites','Retweets','User','UserName','Follower Count','Friend Count', 'User Given Location', 'Place','Coordinates']

In [69]:
df = pd.read_csv('HashtagGreenNewDeal.csv', names = col_names, index_col = 'User' )

In [70]:
df.head()

,Time,Tweet,Favorites,Retweets,UserName,Follower Count,Friend Count,User Given Location,Place,Coordinates
User,,,,,,,,,,
1310625319930322945,2020-09-28 17:00:01,"b""We're organizing every one of the thirteen c...",2,0,TeamJulieOliver,2383,4232,TX-25,NaN,NaN
1310623407814434821,2020-09-28 16:52:25,b'@AOC Can I treat the Congresswoman to her ne...,0,0,AdnanRashid,18725,18996,anndiiiiiiiiiii eee iiii,NaN,NaN
1310621358615719936,2020-09-28 16:44:16,b'@robinskyleigh #GreenNewDeal is the existent...,1,1,sulaviedilejo,1342,4000,"Long Beach, CA",NaN,NaN
1310620478445363203,2020-09-28 16:40:46,b'This is why Penny believes in a #GreenNewDea...,0,0,VentureClimate,95,225,NaN,NaN,NaN
1310618435714535424,2020-09-28 16:32:39,b'Shit like this is why progressive voters do ...,0,0,prettyrickyva,606,1029,"Bon Air, VA",NaN,NaN

In [71]:
df.Tweet.head()

User
1310625319930322945    b"We're organizing every one of the thirteen c...
1310623407814434821    b'@AOC Can I treat the Congresswoman to her ne...
1310621358615719936    b'@robinskyleigh #GreenNewDeal is the existent...
1310620478445363203    b'This is why Penny believes in a #GreenNewDea...
1310618435714535424    b'Shit like this is why progressive voters do ...
Name: Tweet, dtype: object

In [84]:
df = df.astype('object')

for index,row in df.iterrows():
    mentions = []
    urls = []
    hashtags = []
    split_tweet_array = row['Tweet'].split()
    for word in split_tweet_array:
        if word.startswith('b\'@'):
            mentions.append(word[3:])
        if word.startswith('@'):
            mentions.append(word[1:])
        if word.startswith('https:'):
            urls.append(word) 
        if word.startswith('#'):
            hashtags.append(word[1:])
    df.at[index,'Mentions'] = mentions
    df.at[index,'URL'] = urls
    df.at[index,'Hashtags'] = hashtags

In [85]:
df.head()

,Time,Tweet,Favorites,Retweets,UserName,Follower Count,Friend Count,User Given Location,Place,Coordinates,Mentions,URL,Hashtags
User,,,,,,,,,,,,,
1310625319930322945,2020-09-28 17:00:01,"b""We're organizing every one of the thirteen c...",2,0,TeamJulieOliver,2383,4232,TX-25,NaN,NaN,[],"[https://t.co/fLO94a34Ns""]","[TX25, GreenNewDeal]"
1310623407814434821,2020-09-28 16:52:25,b'@AOC Can I treat the Congresswoman to her ne...,0,0,AdnanRashid,18725,18996,anndiiiiiiiiiii eee iiii,NaN,NaN,[AOC],[https://t.co/Ct71Q1cLFV'],[]
1310621358615719936,2020-09-28 16:44:16,b'@robinskyleigh #GreenNewDeal is the existent...,1,1,sulaviedilejo,1342,4000,"Long Beach, CA",NaN,NaN,[robinskyleigh],[],[GreenNewDeal]
1310620478445363203,2020-09-28 16:40:46,b'This is why Penny believes in a #GreenNewDea...,0,0,VentureClimate,95,225,NaN,NaN,NaN,[],[https://t.co/wihFeOOSbd'],[GreenNewDeal]
1310618435714535424,2020-09-28 16:32:39,b'Shit like this is why progressive voters do ...,0,0,prettyrickyva,606,1029,"Bon Air, VA",NaN,NaN,[],[https://t.co/zZ5wvPnCnN'],[]

In [77]:
# Apply a first round of text cleaning techniques
import re
import string

def clean_text_round1(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    text = text[2:]
    #text = re.sub('\[.*?\]', '', text) #remove all information within square brackets (applause queues)
    #text = re.sub('b\'' , '') #remove all bs at the start of tweets
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text) #get rid of all punctuation
    text = re.sub('\w*\d\w*', '', text) #\d is all digits, w is alphanumeric characters * is 0 or more times 
    return text

round1 = lambda x: clean_text_round1(x)

In [78]:
data_clean = pd.DataFrame(df.Tweet.apply(round1))
data_clean

                                                                 Tweet
User
1310625319930322945  were organizing every one of the thirteen coun...
1310623407814434821  aoc can i treat the congresswoman to her next ...
1310621358615719936  robinskyleigh greennewdeal is the existential ...
1310620478445363203  this is why penny believes in a greennewdeal n...
1310618435714535424  shit like this is why progressive voters do no...
...                                                                ...
1307371385312948224  dananessel im from michigan and i will not be ...
1307370579650138113  rachailbabe ragecrayon sapphyreblayze floofyph...
1307368933251584002  yep greennewdeal looks quite mainstream now al...
1307368068721516544  preserving nature is  best protection agst cli...
1307367738084651010  nkla sustainability  hydrogen   percent  comes...

[4044 rows x 1 columns]

In [79]:
# Apply a second round of cleaning
def clean_text_round2(text):
    '''Get rid of some additional punctuation and non-sensical text that was missed the first time around.'''
    text = re.sub('[‘’“”…]', '', text) #get rid of all the quotes 
    text = re.sub('\n', '', text) #get rid of line breaks \n
    return text

round2 = lambda x: clean_text_round2(x)

In [80]:
data_clean = pd.DataFrame(data_clean.Tweet.apply(round2))
data_clean

                                                                 Tweet
User
1310625319930322945  were organizing every one of the thirteen coun...
1310623407814434821  aoc can i treat the congresswoman to her next ...
1310621358615719936  robinskyleigh greennewdeal is the existential ...
1310620478445363203  this is why penny believes in a greennewdeal n...
1310618435714535424  shit like this is why progressive voters do no...
...                                                                ...
1307371385312948224  dananessel im from michigan and i will not be ...
1307370579650138113  rachailbabe ragecrayon sapphyreblayze floofyph...
1307368933251584002  yep greennewdeal looks quite mainstream now al...
1307368068721516544  preserving nature is  best protection agst cli...
1307367738084651010  nkla sustainability  hydrogen   percent  comes...

[4044 rows x 1 columns]

In [86]:
df['Tweet'] = data_clean['Tweet']

In [87]:
df.head()

,Time,Tweet,Favorites,Retweets,UserName,Follower Count,Friend Count,User Given Location,Place,Coordinates,Mentions,URL,Hashtags
User,,,,,,,,,,,,,
1310625319930322945,2020-09-28 17:00:01,were organizing every one of the thirteen coun...,2,0,TeamJulieOliver,2383,4232,TX-25,NaN,NaN,[],"[https://t.co/fLO94a34Ns""]","[TX25, GreenNewDeal]"
1310623407814434821,2020-09-28 16:52:25,aoc can i treat the congresswoman to her next ...,0,0,AdnanRashid,18725,18996,anndiiiiiiiiiii eee iiii,NaN,NaN,[AOC],[https://t.co/Ct71Q1cLFV'],[]
1310621358615719936,2020-09-28 16:44:16,robinskyleigh greennewdeal is the existential ...,1,1,sulaviedilejo,1342,4000,"Long Beach, CA",NaN,NaN,[robinskyleigh],[],[GreenNewDeal]
1310620478445363203,2020-09-28 16:40:46,this is why penny believes in a greennewdeal n...,0,0,VentureClimate,95,225,NaN,NaN,NaN,[],[https://t.co/wihFeOOSbd'],[GreenNewDeal]
1310618435714535424,2020-09-28 16:32:39,shit like this is why progressive voters do no...,0,0,prettyrickyva,606,1029,"Bon Air, VA",NaN,NaN,[],[https://t.co/zZ5wvPnCnN'],[]

## A Look into the Tweets

In [88]:
df.shape

(4044, 13)